config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # LISTAR TODOS RESTAURANTES
  get "restaurants", to: "restaurants#index"

  # MOSTRAR UM FORM PARA O USER CRIAR UM RESTAURANT
  get "restaurants/new", to: "restaurants#new", as: :new_restaurant

  # MOSTRAR UM RESTAURANTE
  get "restaurants/:id", to: "restaurants#show", as: :restaurant

  # CRIAR O RESTAURANTE NO DB
  post "restaurants", to: "restaurants#create"

  # MOSTRAR UM FORM PRO USER EDITAR O RESTAURANT
  get "restaurants/:id/edit", to: "restaurants#edit", as: :edit_restaurant

  # ATUALIZAR O RESTAURANTE NO DB
  patch "restaurants/:id", to: "restaurants#update"

  # DELETAR UM RESTAURANTE
  delete "restaurants/:id", to: "restaurants#destroy", as: :delete

  # resources :restaurants
  # resources :restaurants, except: [:edit, :update]
  # resources :restaurants, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Batch538TheSpoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for (restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%= link_to "criar restaurante", new_restaurant_path %>

<% @restaurants.each do |restaurant| %>
  <ul>
    <li><%= restaurant.name %> <%= link_to "ver", restaurant_path(restaurant) %> | <%= link_to "edit", edit_restaurant_path(restaurant) %> | <%= link_to "deletar", delete_path(restaurant), method: :delete, data: { confirm: "Are you sure?" } %> </li>
  </ul>
<% end %>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %> </h1>

<%= link_to "editar", edit_restaurant_path(@restaurant) %>
<%= link_to "voltar", restaurants_path %>

<p>Address: <%= @restaurant.address %></p>
<p>Rating: <%= @restaurant.rating %> </p>


<%= link_to "Deletar", delete_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } %>